language: node_js
node_js:
  - 8

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn run problems
  - yarn run test

install:
  - yarn install --no-lockfile --non-interactive
